import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";
import crypto from "crypto";

export const runtime = "nodejs";
export const maxDuration = 10;

const SAVE_DIR = path.join(process.cwd(), "public", "saved-videos");

interface SavedVideo {
  id: string;
  filename: string;
  prompt: string;
  provider: string;
  fileSize: number;
  createdAt: string;
  scenes?: number;
}

function ensureDir(d: string) { if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true }); }
function getManifest(): SavedVideo[] {
  const manifestPath = path.join(SAVE_DIR, "manifest.json");
  if (!fs.existsSync(manifestPath)) return [];
  try { return JSON.parse(fs.readFileSync(manifestPath, "utf-8")); }
  catch { return []; }
}
function saveManifest(videos: SavedVideo[]) {
  ensureDir(SAVE_DIR);
  fs.writeFileSync(path.join(SAVE_DIR, "manifest.json"), JSON.stringify(videos, null, 2));
}

export async function GET() {
  try {
    const videos = getManifest();
    return NextResponse.json({ success: true, videos, count: videos.length });
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err?.message }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const { videoUrl, prompt, provider = "unknown", scenes } = await req.json();
    if (!videoUrl || !prompt) return NextResponse.json({ success: false, error: "videoUrl and prompt required." }, { status: 400 });
    ensureDir(SAVE_DIR);
    const id = crypto.createHash("md5").update(`${prompt}-${Date.now()}`).digest("hex").slice(0, 12);
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);

    let videoBuffer: Buffer;
    let ext = "mp4";
    if (videoUrl.startsWith("data:")) {
      const matches = videoUrl.match(/^data:(video\/\w+|image\/\w+);base64,(.+)$/);
      if (!matches) return NextResponse.json({ success: false, error: "Invalid data URL." }, { status: 400 });
      const mimeType = matches[1];
      ext = mimeType.includes("mp4") ? "mp4" : mimeType.includes("webm") ? "webm" : "mp4";
      videoBuffer = Buffer.from(matches[2], "base64");
    } else {
      const res = await fetch(videoUrl, { signal: AbortSignal.timeout(30_000) });
      if (!res.ok) return NextResponse.json({ success: false, error: `Download failed: HTTP ${res.status}` }, { status: 502 });
      videoBuffer = Buffer.from(await res.arrayBuffer());
    }

    const videoFilename = `video_${timestamp}_${id}.${ext}`;
    fs.writeFileSync(path.join(SAVE_DIR, videoFilename), videoBuffer);

    const promptFilename = `video_${timestamp}_${id}_prompt.txt`;
    const promptContent = `DGGCOOL Video — Saved ${new Date().toISOString()}
Provider: ${provider}
${scenes ? `Scenes: ${scenes}\n` : ""}Prompt:
${prompt}

---
Generated by DGGCOOL — Free AI Video & Creative Studio
`;
    fs.writeFileSync(path.join(SAVE_DIR, promptFilename), promptContent);

    const videos = getManifest();
    videos.unshift({ id, filename: videoFilename, prompt: prompt.slice(0, 500), provider, fileSize: videoBuffer.length, createdAt: new Date().toISOString(), scenes });
    saveManifest(videos);

    return NextResponse.json({ success: true, id, filename: videoFilename, downloadUrl: `/saved-videos/${videoFilename}`, promptFile: `/saved-videos/${promptFilename}`, fileSize: videoBuffer.length });
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err?.message }, { status: 500 });
  }
}

export async function DELETE(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const id = searchParams.get("id");
    if (!id) return NextResponse.json({ success: false, error: "id required." }, { status: 400 });
    const videos = getManifest();
    const entry = videos.find(v => v.id === id);
    if (!entry) return NextResponse.json({ success: false, error: "Video not found." }, { status: 404 });
    try { fs.unlinkSync(path.join(SAVE_DIR, entry.filename)); } catch {}
    const promptFile = entry.filename.replace(/\.(mp4|webm)$/, "_prompt.txt");
    try { fs.unlinkSync(path.join(SAVE_DIR, promptFile)); } catch {}
    const filtered = videos.filter(v => v.id !== id);
    saveManifest(filtered);
    return NextResponse.json({ success: true, remaining: filtered.length });
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err?.message }, { status: 500 });
  }
}
